version: '3.8'

services:
  db:
    image: wp-database
    build: "./mysql"
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php:
    image: wordpress-php
    build: "./php"
    container_name: wordpress-php
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_USER_PASSWORD}"
      DB_HOST: db:3306
      WP_ENV: development
      WP_HOME: "http://localhost:8000"
      WP_SITEURL: "http://localhost:8000/wp"
      AUTH_KEY: "${WP_AUTH_KEY}"
      SECURE_AUTH_KEY: "${WP_SECURE_AUTH_KEY}"
      LOGGED_IN_KEY: "${WP_LOGGED_IN_KEY}"
      NONCE_KEY: "${WP_NONCE_KEY}"
      AUTH_SALT: "${WP_AUTH_SALT}"
      SECURE_AUTH_SALT: "${WP_SECURE_AUTH_SALT}"
      LOGGED_IN_SALT: "${WP_LOGGED_IN_SALT}"
      NONCE_SALT: "${WP_NONCE_SALT}"
    volumes:
      - ./wordpress:/var/www/html

  nginx:
    image: wordpress-nginx
    build: './nginx'
    depends_on:
      - php
    restart: unless-stopped
    environment:
      - PHP_HOST=php
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_USER_PASSWORD}"
    ports:
      - "8080:80"

volumes:
  mysql:
