name: Update website content - integration

on:
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/deploy-frontend.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT: Integration
